version: '2'

services:
  web:
    build: . # where Dockerfile is
    image: '$AWS_ECR_URL/$PROJECT_NAME/rest-api:$IMAGE_TAG'
    ports:
      - "80:80"
    # volumes:
    # environment:
    #   - MONGODB_URI=${MONGODB_URI}
    #   - NODE_ENV=${NODE_ENV}
    # depends_on:
    logging:
      driver: "awslogs"
      options:
          awslogs-region: "us-east-2"
          awslogs-group: "/ecs/${PROJECT_NAME}-task-def"
          awslogs-stream-prefix: "ecs"
